package br.edu.fatec2019.conducaoTests;

import java.awt.AWTException;
import java.awt.Robot;
import java.awt.event.KeyEvent;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import com.sun.javafx.css.StyleCache.Key;

public class CompraTest 
{	public static void main(String[] args) throws InterruptedException
	{	String path = "junit\\chromedriver.exe";
		System.setProperty("webdriver.chrome.driver", path);
		WebDriver driver = new ChromeDriver();
		Thread thread = new Thread();
		if(driver != null)
		{	driver.get("http://localhost:8080/ProjetoLES2019/principal.html");
			driver.manage().window().maximize();
			thread.sleep(2000);
			driver.findElement(By.linkText("Aluno")).click();
			thread.sleep(1000);
			driver.get("http://localhost:8080/ProjetoLES2019/loginAluno.html");
			driver.findElement(By.id("email")).sendKeys("eduardo@gmail.com");
			thread.sleep(1000);
			driver.findElement(By.id("senha")).sendKeys("!@#Abc123");
			thread.sleep(1000);
			driver.findElement(By.linkText("Entrar")).click();
			thread.sleep(1000);
			driver.get("http://localhost:8080/ProjetoLES2019/inicialAluno.jsp");
			driver.findElement(By.linkText("Meus Cupons")).click();
			thread.sleep(1000);
			driver.get("http://localhost:8080/ProjetoLES2019/meusCupons.jsp");
			driver.findElement(By.linkText("Cursos")).click();
			thread.sleep(1000);
			driver.get("http://localhost:8080/ProjetoLES2019/cursos_compra.jsp");
			driver.findElement(By.partialLinkText("Angular")).click();
			thread.sleep(3000);
			driver.get("http://localhost:8080/ProjetoLES2019/curso_informacao.jsp");
			driver.findElement(By.linkText("Comprar")).click();
			thread.sleep(3000);
			driver.get("http://localhost:8080/ProjetoLES2019/meuCarrinho.jsp");
			driver.findElement(By.linkText("Continuar Comprando")).click();
			thread.sleep(3000);
			driver.get("http://localhost:8080/ProjetoLES2019/cursos_compra.jsp");
			driver.findElement(By.partialLinkText("Python")).click();
			thread.sleep(3000);
			driver.get("http://localhost:8080/ProjetoLES2019/curso_informacao2.jsp");
			driver.findElement(By.linkText("Comprar")).click();
			thread.sleep(3000);
			driver.get("http://localhost:8080/ProjetoLES2019/meuCarrinho2.jsp");
			driver.findElement(By.linkText("Continuar Comprando")).click();
			thread.sleep(3000);
			driver.get("http://localhost:8080/ProjetoLES2019/cursos_compra.jsp");
			driver.findElement(By.partialLinkText("Objetos")).click();
			thread.sleep(3000);
			driver.get("http://localhost:8080/ProjetoLES2019/curso_informacao3.jsp");
			driver.findElement(By.linkText("Comprar")).click();
			thread.sleep(3000);
			driver.get("http://localhost:8080/ProjetoLES2019/meuCarrinho3.jsp");
			driver.findElement(By.linkText("Continuar Comprando")).click();
			thread.sleep(3000);
			driver.get("http://localhost:8080/ProjetoLES2019/cursos_compra.jsp");
			driver.findElement(By.partialLinkText("Photoshop")).click();
			thread.sleep(3000);
			driver.get("http://localhost:8080/ProjetoLES2019/curso_informacao4.jsp");
			driver.findElement(By.linkText("Comprar")).click();
			thread.sleep(3000);
			driver.get("http://localhost:8080/ProjetoLES2019/meuCarrinho4.jsp");
			driver.findElement(By.id("cupom1")).sendKeys("CT000000101");
			thread.sleep(1000);
			driver.findElement(By.id("addCupom")).click();
			thread.sleep(1000);
			driver.switchTo().alert().accept();
			thread.sleep(1000);
			driver.findElement(By.linkText("Finalizar")).click();
			thread.sleep(1000);
			driver.findElement(By.linkText("Pedido")).click();
			thread.sleep(3000);
			driver.findElement(By.linkText("Forma de Pagamento")).click();
			thread.sleep(1000);
			driver.findElement(By.id("outros")).click();
			thread.sleep(1000);
			driver.findElement(By.linkText("adicionar novo cartão")).click();
			thread.sleep(1000);
			driver.get("http://localhost:8080/ProjetoLES2019/addCartao.jsp");
			driver.findElement(By.id("cardName")).sendKeys("Eduardo W Murakoshi");
			thread.sleep(1000);
			driver.findElement(By.id("cardNumber")).sendKeys("1234567890124567");
			thread.sleep(1000);
			driver.findElement(By.id("seg")).sendKeys("123");
			thread.sleep(1000);
			driver.findElement(By.id("validade")).sendKeys("10");
			thread.sleep(1000);
			driver.findElement(By.id("validade")).sendKeys("09");
			thread.sleep(1000);
			driver.findElement(By.id("validade")).sendKeys("2030");
			driver.findElement(By.linkText("Salvar Dados")).click();
			thread.sleep(1000);
			driver.get("http://localhost:8080/ProjetoLES2019/pagamento2.jsp");
			driver.findElement(By.linkText("Forma de Pagamento")).click();
			driver.findElement(By.id("id_qtde")).clear();
			driver.findElement(By.id("id_qtde")).sendKeys("2");
			driver.findElement(By.id("id_qtde")).click();
			thread.sleep(1000);
			driver.findElement(By.id("ajustar")).click();
			thread.sleep(1000);
			driver.findElement(By.id("outros")).click();
			thread.sleep(1000);
			driver.findElement(By.name("card")).click();
			thread.sleep(1000);
			driver.findElement(By.id("save")).click();
			thread.sleep(1000);
			driver.switchTo().alert().accept();
			thread.sleep(1000);
			driver.get("http://localhost:8080/ProjetoLES2019/pagamento2.jsp");
			thread.sleep(1000);
			driver.findElement(By.linkText("Finalizar Compra")).click();
			thread.sleep(1000);
			driver.findElement(By.id("email")).sendKeys("eduardowmu@yahoo.com.br");
			thread.sleep(1000);
			driver.findElement(By.id("compra")).click();
			thread.sleep(1000);
			driver.switchTo().alert().accept();
			thread.sleep(1000);
			driver.get("http://localhost:8080/ProjetoLES2019/inicialAluno.jsp");
			driver.findElement(By.linkText("Meus Cursos")).click();
			thread.sleep(1000);
			driver.get("http://localhost:8080/ProjetoLES2019/meusCursos.jsp");
			driver.findElement(By.xpath("<a href=\"#\"><img src=\"imagens/troca.png\"></a>")).click();
			thread.sleep(1000);
			driver.switchTo().alert().accept();
			thread.sleep(1000);
			
		}
	}
}